# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfd4d55a45d211aa5c862e88e2d8ee8656b0d6596e35d163c3db32a676d70424aa9562bd63133eaadb6c5fe4f695313c80119f7d73c9986c1a3ce985ed994bc2

test:
  secret_key_base: 56ae8d167183139c1f93d526dda753f7780353f27491e4f1b9bf41f6b7f714733fd504b2cd8dea93da201db1e74e577170bf25c076bec3d7a47d3ec9404f6fd6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
